# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include: 
    - master2
  paths:
    exclude: 
      - CI
variables:
  - group: IotExample
  - group: keyvaultepm

stages:
- stage: DeployIaCIOT
  displayName: Deploy IaC IOT
  jobs:
  - deployment: DeployDeployIaCIOTJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'IOT-DEV-stpc'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
        
          - task: AzureCLI@1
            displayName: 'Azure CLI to deploy required Azure resources'
            inputs:
              azureSubscription: 'VS Ent-MPN- ODIAZ (972e401d-226e-48c7-a463-6d562c39edda)'
              scriptLocation: inlineScript
              inlineScript: |
                # this will create Azure resource group
                az group create --location eastus --name $(var.terraformstoragerg)
                az storage account create --name $(var.terraformstorageaccount) --resource-group $(var.terraformstoragerg) --location eastus --sku Standard_LRS
                az storage container create --name $(var.terraformContainername) --account-name $(var.terraformstorageaccount)
                az storage account keys list -g $(var.terraformstoragerg) -n $(var.terraformstorageaccount)
                key=$(az storage account keys list -g $(var.terraformstoragerg) -n $(var.terraformstorageaccount) --query [0].value -o tsv)
                echo $key
                echo "##vso[task.setvariable variable=storagekey]$key"
            enabled: false

          - task: replacetokens@3
            inputs:
              targetFiles: '**/*.tf'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'
              useLegacyPattern: false
              enableTelemetry: true

          - task: TerraformInstaller@0
            displayName: 'terraform installer'
            inputs:
              terraformVersion: '0.13.5'
            enabled: true

          - task: TerraformTaskV1@0
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
              backendServiceArm: 'VS Ent-MPN- ODIAZ (972e401d-226e-48c7-a463-6d562c39edda)'
              backendAzureRmResourceGroupName: '$(var.terraformstoragerg)'
              backendAzureRmStorageAccountName: '$(var.terraformstorageaccount)'
              backendAzureRmContainerName: '$(var.terraformContainername)'
              backendAzureRmKey: '$(var.terraformstoragekey)'
            enabled: true


          - task: TerraformTaskV1@0
            displayName: 'Terraform validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
            enabled: true

          - task: TerraformTaskV1@0
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
              environmentServiceNameAzureRM: 'VS Ent-MPN- ODIAZ (972e401d-226e-48c7-a463-6d562c39edda)'
            enabled: true

          - task: TerraformTaskV1@0
            displayName: 'Terraform : apply -auto-approve'
            inputs:
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'VS Ent-MPN- ODIAZ (972e401d-226e-48c7-a463-6d562c39edda)'
              backendAzureRmResourceGroupName: '$(var.terraformstoragerg)'
              backendAzureRmStorageAccountName: '$(var.terraformstorageaccount) '
              backendAzureRmContainerName: $(var.terraformContainername)
              backendAzureRmKey: '$(var.terraformstoragekey)'
            enabled: false
          - task: TerraformTaskV1@0
            displayName: 'Terraform destroy'
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
              environmentServiceNameAzureRM: 'VS Ent-MPN- ODIAZ (972e401d-226e-48c7-a463-6d562c39edda)'
            enabled: ture

- stage: Installmachine
  displayName: 'Install Machine Components'
  dependsOn: DeployIaCIOT
  jobs:
  - deployment: deployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'IOT-DEV2'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo  $(var.resourcevmadminpassword) | ssh $(var.resourcevmadminuser)@$(var.ipvmlinux)
                ls